import type { WorldArea } from './types';

export const worldAreas: WorldArea[] = [
  {
    id: 'starting-village',
    name: 'はじまりの まち',
    shortName: 'まち',
    theme: 'village',
    order: 1,
    initiallyUnlocked: true,
    requiredPreviousAreaId: null,
    requiredRecoveryStage: 0,
    enemyIds: [
      'enemy-moji-slime',
      'enemy-kotoba-puni',
      'enemy-pencil-sprout',
      'enemy-erasing-dust',
      'enemy-card-mimic',
      'enemy-ink-hop',
      'enemy-note-bird',
      'enemy-hira-wisp',
      'enemy-star-syllable',
    ],
    bossEnemyId: 'boss-village-kana-guardian',
  },
  {
    id: 'word-forest',
    name: 'ことばの もり',
    shortName: 'もり',
    theme: 'forest',
    order: 2,
    initiallyUnlocked: false,
    requiredPreviousAreaId: 'starting-village',
    requiredRecoveryStage: 3,
    enemyIds: [
      'enemy-hidden-moji',
      'enemy-leaf-letter',
      'enemy-moss-kana',
      'enemy-seed-scribe',
      'enemy-guruguru-bat',
      'enemy-branch-riddle',
      'enemy-forest-echo',
      'enemy-vine-word',
      'enemy-green-orthos',
    ],
    bossEnemyId: 'boss-forest-kotodama',
  },
  {
    id: 'picture-hill',
    name: 'えあわせの おか',
    shortName: 'おか',
    theme: 'hill',
    order: 3,
    initiallyUnlocked: false,
    requiredPreviousAreaId: 'word-forest',
    requiredRecoveryStage: 2,
    enemyIds: [
      'enemy-moya-ghost',
      'enemy-picture-puff',
      'enemy-color-kana',
      'enemy-shape-moth',
      'enemy-frame-fairy',
      'enemy-cloud-letter',
      'enemy-rainbow-smudge',
      'enemy-sketched-wolf',
      'enemy-gallery-dragon',
    ],
    bossEnemyId: 'boss-hill-picturephinx',
  },
  {
    id: 'ordering-cave',
    name: 'ならべの どうくつ',
    shortName: 'どうくつ',
    theme: 'cave',
    order: 4,
    initiallyUnlocked: false,
    requiredPreviousAreaId: 'picture-hill',
    requiredRecoveryStage: 2,
    enemyIds: [
      'enemy-magic-kinoko',
      'enemy-order-pebble',
      'enemy-echo-kana',
      'enemy-cave-scroll',
      'enemy-ink-golem',
      'enemy-flip-bat',
      'enemy-grammar-geode',
      'enemy-rune-mole',
      'enemy-crystal-syntax',
    ],
    bossEnemyId: 'boss-cave-order-king',
  },
  {
    id: 'word-castle',
    name: 'もじの おしろ',
    shortName: 'おしろ',
    theme: 'castle',
    order: 5,
    initiallyUnlocked: false,
    requiredPreviousAreaId: 'ordering-cave',
    requiredRecoveryStage: 3,
    enemyIds: [
      'enemy-castle-scribe',
      'enemy-armor-kana',
      'enemy-banner-bat',
      'enemy-tower-wisp',
      'enemy-dakuten-ghost',
      'enemy-question-ghost',
      'enemy-silver-syllable',
      'enemy-royal-moji',
      'enemy-legend-lexicon',
    ],
    bossEnemyId: 'boss-mojinexus',
  },
];

export function getWorldArea(areaId: string) {
  return worldAreas.find((area) => area.id === areaId);
}
