import type { CompanionData } from './types';

export const companionData: CompanionData[] = [
  {
    id: 'rabbit',
    name: 'うさぎ',
    species: 'うさぎ',
    description: 'もじを さがすのが とくい',
    skillId: 'reduce-choice',
    skillName: 'ひとつ すっきり',
    skillDescription: 'えらぶ ものを ひとつ へらすよ',
    preferredMissionTypes: ['letter-search', 'similar-letter-choice'],
    unlockCondition: {
      type: 'area-stage',
      areaId: 'starting-village',
      stage: 1,
    },
    imageId: '🐰',
    active: true,
  },
  {
    id: 'fox',
    name: 'きつね',
    species: 'きつね',
    description: 'えと もじを つなげるよ',
    skillId: 'illustration-hint',
    skillName: 'えの ヒント',
    skillDescription: 'えの もんだいで ヒントを だすよ',
    preferredMissionTypes: [
      'illustration-letter-choice',
      'illustration-word-choice',
    ],
    unlockCondition: { type: 'area-unlocked', areaId: 'word-forest' },
    imageId: '🦊',
    active: true,
  },
  {
    id: 'bear',
    name: 'くま',
    species: 'くま',
    description: 'ことばを ゆっくり みるよ',
    skillId: 'word-candidate-sort',
    skillName: 'ならべて みよう',
    skillDescription: 'ことばの こうほを みやすくするよ',
    preferredMissionTypes: ['word-completion', 'text-search'],
    unlockCondition: { type: 'area-unlocked', areaId: 'picture-hill' },
    imageId: '🐻',
    active: true,
  },
  {
    id: 'owl',
    name: 'ふくろう',
    species: 'ふくろう',
    description: 'ふくしゅうを みまもるよ',
    skillId: 'gentle-review',
    skillName: 'やさしい ふくしゅう',
    skillDescription: 'ふくしゅうを やさしく はじめるよ',
    preferredMissionTypes: ['letter-introduction', 'letter-search'],
    unlockCondition: { type: 'weak-mastered', count: 1 },
    imageId: '🦉',
    active: true,
  },
  {
    id: 'squirrel',
    name: 'りす',
    species: 'りす',
    description: 'ごほうびを みつけるよ',
    skillId: 'bonus-gold',
    skillName: 'きらり みつけた',
    skillDescription: 'たまに ゴールドが すこし ふえるよ',
    preferredMissionTypes: ['horizontal-reading', 'vertical-reading'],
    unlockCondition: { type: 'normal-victories', count: 3 },
    imageId: '🐿️',
    active: true,
  },
];
