import type { EquipmentData } from './types';

export const EQUIPMENT_BONUS_LIMITS = {
  attackBonus: 5,
  rewardBonus: 3,
} as const;

export const equipmentData: EquipmentData[] = [
  {
    id: 'moji-staff',
    name: 'もじのつえ',
    type: 'weapon',
    description: 'やさしく ひかる つえ',
    price: 20,
    unlockCondition: { type: 'always' },
    imageId: '🪄',
    cosmeticStyle: 'staff',
    attackBonus: 1,
    rewardBonus: 0,
    active: true,
  },
  {
    id: 'light-pencil',
    name: 'ひかりのえんぴつ',
    type: 'weapon',
    description: 'ことばを てらす えんぴつ',
    price: 35,
    unlockCondition: {
      type: 'area-stage',
      areaId: 'starting-village',
      stage: 2,
    },
    imageId: '✏️',
    cosmeticStyle: 'pencil',
    attackBonus: 2,
    rewardBonus: 0,
    active: true,
  },
  {
    id: 'word-sword',
    name: 'ことばのけん',
    type: 'weapon',
    description: 'まよいを はらう けん',
    price: 60,
    unlockCondition: { type: 'area-unlocked', areaId: 'word-castle' },
    imageId: '⚔️',
    cosmeticStyle: 'sword',
    attackBonus: 3,
    rewardBonus: 1,
    active: true,
  },
  {
    id: 'adventure-cloak',
    name: 'ぼうけんマント',
    type: 'armor',
    description: 'あるくのが たのしくなる',
    price: 20,
    unlockCondition: { type: 'always' },
    imageId: '🧣',
    cosmeticStyle: 'cloak',
    attackBonus: 0,
    rewardBonus: 1,
    active: true,
  },
  {
    id: 'forest-hat',
    name: 'もりのぼうし',
    type: 'armor',
    description: 'はっぱの かたちの ぼうし',
    price: 35,
    unlockCondition: { type: 'area-unlocked', areaId: 'word-forest' },
    imageId: '🎩',
    cosmeticStyle: 'forest-hat',
    attackBonus: 1,
    rewardBonus: 1,
    active: true,
  },
  {
    id: 'star-armor',
    name: 'ほしのよろい',
    type: 'armor',
    description: 'ほしが きらっと ひかる',
    price: 65,
    unlockCondition: { type: 'boss-defeated', count: 1 },
    imageId: '🌟',
    cosmeticStyle: 'star-armor',
    attackBonus: 2,
    rewardBonus: 2,
    active: true,
  },
  {
    id: 'flower-badge',
    name: 'はなのバッジ',
    type: 'accessory',
    description: 'はなが さいた しるし',
    price: 15,
    unlockCondition: {
      type: 'area-stage',
      areaId: 'starting-village',
      stage: 1,
    },
    imageId: '🌼',
    cosmeticStyle: 'flower-badge',
    attackBonus: 0,
    rewardBonus: 1,
    active: true,
  },
  {
    id: 'word-ring',
    name: 'ことばのゆびわ',
    type: 'accessory',
    description: 'ことばを つなぐ ゆびわ',
    price: 45,
    unlockCondition: { type: 'companion-joined', companionId: 'fox' },
    imageId: '💍',
    cosmeticStyle: 'word-ring',
    attackBonus: 1,
    rewardBonus: 2,
    active: true,
  },
  {
    id: 'rainbow-medal',
    name: 'にじのメダル',
    type: 'accessory',
    description: 'がんばりが にじになる',
    price: 80,
    unlockCondition: { type: 'area-stage', areaId: 'word-castle', stage: 3 },
    imageId: '🏅',
    cosmeticStyle: 'rainbow-medal',
    attackBonus: 2,
    rewardBonus: 3,
    active: true,
  },
  {
    id: 'bronze-sword',
    name: 'ブロンズソード',
    type: 'weapon',
    description: 'ぼうけんに なれてきたら つかえる けん',
    price: 90,
    unlockCondition: { type: 'area-unlocked', areaId: 'picture-hill' },
    imageId: 'bronze-sword',
    cosmeticStyle: 'bronze-sword',
    attackBonus: 3,
    rewardBonus: 1,
    active: true,
  },
  {
    id: 'silver-sword',
    name: 'シルバーソード',
    type: 'weapon',
    description: 'ならべるちからを のばす けん',
    price: 150,
    unlockCondition: { type: 'area-unlocked', areaId: 'ordering-cave' },
    imageId: 'silver-sword',
    cosmeticStyle: 'silver-sword',
    attackBonus: 4,
    rewardBonus: 1,
    active: true,
  },
  {
    id: 'gold-sword',
    name: 'ゴールドソード',
    type: 'weapon',
    description: 'さいごの ぼうけんを てらす けん',
    price: 240,
    unlockCondition: { type: 'boss-defeated', count: 2 },
    imageId: 'gold-sword',
    cosmeticStyle: 'gold-sword',
    attackBonus: 5,
    rewardBonus: 2,
    active: true,
  },
  {
    id: 'leather-helm',
    name: 'レザーヘルム',
    type: 'armor',
    description: 'あたまを まもる かるい ぼうぐ',
    price: 75,
    unlockCondition: { type: 'area-stage', areaId: 'word-forest', stage: 2 },
    imageId: 'leather-helm',
    cosmeticStyle: 'leather-helm',
    attackBonus: 1,
    rewardBonus: 2,
    active: true,
  },
  {
    id: 'silver-helm',
    name: 'シルバーヘルム',
    type: 'armor',
    description: 'むずかしい もじにも まけない ぼうぐ',
    price: 160,
    unlockCondition: { type: 'area-stage', areaId: 'ordering-cave', stage: 3 },
    imageId: 'silver-helm',
    cosmeticStyle: 'silver-helm',
    attackBonus: 2,
    rewardBonus: 2,
    active: true,
  },
  {
    id: 'wisdom-pendant',
    name: 'ちえのペンダント',
    type: 'accessory',
    description: 'ふくしゅうの ひらめきを くれるよ',
    price: 180,
    unlockCondition: { type: 'companion-joined', companionId: 'owl' },
    imageId: 'wisdom-pendant',
    cosmeticStyle: 'wisdom-pendant',
    attackBonus: 1,
    rewardBonus: 3,
    active: true,
  },
];
